//lib/core/services/drug_database_seeder.dart
import 'package:flutter/foundation.dart';
import '../models/drug.dart';
import 'drug_supabase_service.dart';

/// Service for seeding the drug database with common ICU medications
class DrugDatabaseSeeder {
  final DrugSupabaseService _supabaseService = DrugSupabaseService();

  /// Seed the database with common ICU medications
  Future<void> seedDatabase() async {
    debugPrint('Starting drug database seeding...');

    final drugs = _getCommonICUDrugs();

    int successCount = 0;
    int failCount = 0;

    for (final drug in drugs) {
      try {
        await _supabaseService.upsertDrug(drug);
        successCount++;
        debugPrint('✓ Seeded: ${drug.genericName}');
      } catch (e) {
        failCount++;
        debugPrint('✗ Failed to seed ${drug.genericName}: $e');
      }
    }

    debugPrint('\nSeeding complete:');
    debugPrint('  Success: $successCount');
    debugPrint('  Failed: $failCount');
  }

  /// Get list of common ICU medications
  List<Drug> _getCommonICUDrugs() {
    return [
      // ANALGESICS
      Drug(
        id: 'RX1199',
        genericName: 'Morphine',
        tradeNames: ['MS Contin', 'Avinza', 'Kadian'],
        drugClass: 'Opioid Analgesic',
        mechanism: 'Mu-opioid receptor agonist',
        indications: ['Moderate to severe pain', 'Acute pulmonary edema'],
        contraindications: [
          'Respiratory depression',
          'Severe asthma',
          'Paralytic ileus',
          'Hypersensitivity',
        ],
        warnings: [
          'Respiratory depression',
          'Physical dependence',
          'Constipation',
          'Hypotension',
        ],
        blackBoxWarnings: [
          'Life-threatening respiratory depression',
          'Accidental ingestion',
          'Neonatal opioid withdrawal syndrome',
          'Risks from concomitant use with benzodiazepines',
        ],
        sideEffects: [
          'Nausea',
          'Vomiting',
          'Constipation',
          'Drowsiness',
          'Confusion',
          'Urinary retention',
          'Pruritus',
        ],
        commonSideEffects: ['Constipation', 'Nausea', 'Drowsiness', 'Vomiting'],
        seriousSideEffects: [
          'Respiratory depression',
          'Hypotension',
          'Cardiac arrest',
        ],
        standardDoseIndication: 'Pain management',
        standardDoseRoute: 'IV',
        standardDose: '2-4 mg',
        standardDoseFrequency: 'q2-4h PRN',
        standardDoseNotes:
            'Titrate to effect; start low in opioid-naive patients',
        geriatricNotes: 'Reduce dose by 25-50%; start at lowest effective dose',
        maxDailyDose: 'No maximum; dose titrated to effect',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing with caution',
        renalCrcl10_30: 'Reduce dose by 25-50%; extend dosing interval',
        renalCrclLt10: 'Reduce dose by 50%; avoid if possible',
        renalDialysis: 'Supplemental dose after dialysis (3-4 hr session)',
        renalNotes: 'M6G metabolite accumulates in renal impairment',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes: 'Severe hepatic impairment contraindicated',
      ),

      Drug(
        id: 'RX1979',
        genericName: 'Fentanyl',
        tradeNames: ['Sublimaze', 'Duragesic', 'Actiq'],
        drugClass: 'Opioid Analgesic',
        mechanism:
            'Mu-opioid receptor agonist (100x more potent than morphine)',
        indications: [
          'Breakthrough pain',
          'Anesthesia adjunct',
          'Chronic pain (transdermal)',
        ],
        contraindications: [
          'Hypersensitivity',
          'Severe respiratory depression',
          'MAOI use within 14 days',
        ],
        warnings: [
          'Respiratory depression',
          'Addiction potential',
          'CNS depression',
        ],
        blackBoxWarnings: [
          'Life-threatening respiratory depression',
          'Accidental exposure',
          'Cytochrome P450 3A4 interaction',
        ],
        sideEffects: [
          'Respiratory depression',
          'Chest wall rigidity',
          'Bradycardia',
          'Hypotension',
          'Nausea',
          'Confusion',
        ],
        commonSideEffects: ['Nausea', 'Dizziness', 'Drowsiness'],
        seriousSideEffects: [
          'Respiratory arrest',
          'Cardiac arrhythmias',
          'Anaphylaxis',
        ],
        standardDoseIndication: 'Sedation/Analgesia',
        standardDoseRoute: 'IV',
        standardDose: '0.5-1 mcg/kg',
        standardDoseFrequency: 'PRN or infusion 0.5-2 mcg/kg/h',
        standardDoseNotes: 'Rapid onset (1-2 min); short duration (30-60 min)',
        geriatricNotes: 'Reduce initial dose by 50%',
        maxDailyDose: 'Individualized based on patient response',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Reduce dose by 25%',
        renalCrclLt10: 'Reduce dose by 50%',
        renalDialysis: 'Not significantly removed by dialysis',
        renalNotes: 'Use with caution; monitor for prolonged effects',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes: 'Metabolized by CYP3A4; avoid with severe impairment',
      ),

      Drug(
        id: 'RX2017',
        genericName: 'Acetaminophen',
        tradeNames: ['Tylenol', 'Panadol', 'Adol'],
        drugClass: 'Analgesic, Antipyretic',
        mechanism:
            'Central inhibition of COX; effects on endocannabinoid system',
        indications: ['Mild to moderate pain', 'Fever'],
        contraindications: ['Severe hepatic impairment', 'Hypersensitivity'],
        warnings: [
          'Hepatotoxicity',
          'Skin reactions',
          'Contains in combination products',
        ],
        blackBoxWarnings: [
          'Hepatotoxicity - acute liver failure at doses >4000mg/day',
        ],
        sideEffects: [
          'Hepatotoxicity (overdose)',
          'Nausea',
          'Rash',
          'Thrombocytopenia',
        ],
        commonSideEffects: ['Rare at therapeutic doses'],
        seriousSideEffects: ['Liver failure', 'Necrosis', 'Death (overdose)'],
        standardDoseIndication: 'Pain/Fever',
        standardDoseRoute: 'PO/IV',
        standardDose: '325-650 mg (PO), 1000 mg (IV)',
        standardDoseFrequency: 'q4-6h PRN',
        standardDoseNotes: 'IV dose limited to 6 doses/day; max 4000mg/day',
        geriatricNotes: 'Max 3000mg/day; monitor liver function',
        maxDailyDose:
            '4000 mg (3000 mg in elderly, chronic alcohol use, liver disease)',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Max 3000mg/day; extend interval to q6h',
        renalCrcl10_30: 'Max 2000mg/day; extend interval to q8h',
        renalCrclLt10: 'Avoid or max 2000mg/day',
        renalDialysis: 'Supplemental dose after dialysis',
        renalNotes: 'Dose reduction recommended in severe renal impairment',
        hepaticChildPughA: 'Max 2000mg/day',
        hepaticChildPughB: 'Max 1000mg/day or avoid',
        hepaticChildPughC: 'Contraindicated',
        hepaticNotes: 'Avoid in severe hepatic impairment',
      ),

      // SEDATIVES/HYPNOTICS
      Drug(
        id: 'RX1938',
        genericName: 'Midazolam',
        tradeNames: ['Versed'],
        drugClass: 'Benzodiazepine',
        mechanism: 'GABA-A receptor agonist',
        indications: [
          'Preoperative sedation',
          'Procedural sedation',
          'ICU sedation',
          'Status epilepticus',
        ],
        contraindications: [
          'Hypersensitivity',
          'Acute narrow-angle glaucoma',
          'Severe respiratory insufficiency',
        ],
        warnings: [
          'Respiratory depression',
          'Hypotension',
          'Paradoxical reactions',
          'Amnesia',
          'Dependence',
        ],
        blackBoxWarnings: [
          'Risks from concomitant use with opioids',
          'Abuse, misuse, and addiction',
        ],
        sideEffects: [
          'Respiratory depression',
          'Hypotension',
          'Apnea',
          'Nausea',
          'Vomiting',
          'Agitation',
        ],
        commonSideEffects: ['Hypotension', 'Respiratory depression', 'Amnesia'],
        seriousSideEffects: [
          'Cardiac arrest',
          'Respiratory arrest',
          'Anaphylaxis',
        ],
        standardDoseIndication: 'Procedural Sedation',
        standardDoseRoute: 'IV',
        standardDose: '0.02-0.05 mg/kg',
        standardDoseFrequency: 'Single dose; may repeat',
        standardDoseNotes: 'Onset 1-5 min; duration 1-2 hours',
        geriatricNotes: 'Reduce initial dose by 50%; use 0.5-1 mg',
        maxDailyDose: 'Individualized based on response',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Reduce dose by 25-50%',
        renalCrclLt10: 'Reduce dose by 50%',
        renalDialysis: 'Accumulates; reduce dose',
        renalNotes: 'Use with caution; monitor for prolonged sedation',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes:
            'Metabolized by CYP3A4; significantly affected by liver disease',
      ),

      Drug(
        id: 'RX1937',
        genericName: 'Lorazepam',
        tradeNames: ['Ativan'],
        drugClass: 'Benzodiazepine',
        mechanism: 'GABA-A receptor agonist',
        indications: [
          'Anxiety',
          'Insomnia',
          'Alcohol withdrawal',
          'Preoperative sedation',
          'Seizures (adjunct)',
        ],
        contraindications: [
          'Hypersensitivity',
          'Acute narrow-angle glaucoma',
          'Severe respiratory insufficiency',
        ],
        warnings: [
          'Respiratory depression',
          'Sedation',
          'Dependence',
          'Paradoxical reactions',
        ],
        blackBoxWarnings: [
          'Risks from concomitant use with opioids',
          'Abuse, misuse, and addiction',
        ],
        sideEffects: [
          'Sedation',
          'Dizziness',
          'Weakness',
          'Unsteadiness',
          'Respiratory depression',
          'Amnesia',
        ],
        commonSideEffects: ['Drowsiness', 'Sedation', 'Dizziness'],
        seriousSideEffects: [
          'Respiratory arrest',
          'Hypotension',
          'Seizures (withdrawal)',
        ],
        standardDoseIndication: 'Anxiety/Sedation',
        standardDoseRoute: 'PO/IV/IM',
        standardDose: '0.5-2 mg',
        standardDoseFrequency: 'q4-6h PRN',
        standardDoseNotes:
            'IV onset 15-30 min; IM absorption variable; PO onset 1-2 hours',
        geriatricNotes: 'Start 0.5-1 mg; max 2mg/day',
        maxDailyDose: '10 mg/day',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing with caution',
        renalCrclLt10: 'Reduce dose by 25-50%',
        renalDialysis: 'Not significantly removed',
        renalNotes:
            'Metabolized by glucuronidation; relatively safe in renal impairment',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes:
            'Use with caution; prolonged half-life in severe liver disease',
      ),

      Drug(
        id: 'RX2002',
        genericName: 'Propofol',
        tradeNames: ['Diprivan'],
        drugClass: 'General Anesthetic',
        mechanism: 'GABA-A receptor modulator',
        indications: ['Sedation', 'Anesthesia induction', 'ICU sedation'],
        contraindications: [
          'Hypersensitivity to soy/eggs',
          'Severe hypotension',
        ],
        warnings: [
          'Hypotension',
          'Respiratory depression',
          'Pain on injection',
          'Hypertriglyceridemia',
          'Infection risk (contamination)',
        ],
        blackBoxWarnings: [
          'Risks of sedation in non-critical care settings',
          'Propofol Infusion Syndrome (PRIS)',
        ],
        sideEffects: [
          'Hypotension',
          'Apnea',
          'Bradycardia',
          'Pain on injection',
          'Nausea',
          'Hypertriglyceridemia',
        ],
        commonSideEffects: ['Hypotension', 'Apnea', 'Bradycardia'],
        seriousSideEffects: [
          'Propofol Infusion Syndrome (metabolic acidosis, rhabdomyolysis, cardiac failure)',
          'Cardiac arrest',
          'Seizures',
        ],
        standardDoseIndication: 'ICU Sedation',
        standardDoseRoute: 'IV',
        standardDose: '5-50 mcg/kg/min',
        standardDoseFrequency: 'Continuous infusion',
        standardDoseNotes:
            'Titrate to sedation score; max 4 hours at >4mg/kg/h',
        geriatricNotes: 'Reduce infusion rate by 30-50%',
        maxDailyDose:
            'Individualized; do not exceed 4 mg/kg/h for >4 hours (PRIS risk)',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing with caution',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'Cleared by liver; no dose adjustment needed',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Reduce dose by 75% or avoid',
        hepaticNotes:
            'Metabolized by liver; use with caution in severe impairment',
      ),

      // NEUROMUSCULAR BLOCKING AGENTS
      Drug(
        id: 'RX3160',
        genericName: 'Rocuronium',
        tradeNames: ['Zemuron'],
        drugClass: 'Non-depolarizing Neuromuscular Blocker',
        mechanism: 'Competitive nicotinic acetylcholine receptor antagonist',
        indications: [
          'Adjunct to general anesthesia',
          'Facilitate endotracheal intubation',
          'ICU paralysis',
        ],
        contraindications: [
          'Hypersensitivity',
          'Known or suspected genetic susceptibility to malignant hyperthermia',
        ],
        warnings: [
          'Prolonged paralysis',
          'Anaphylaxis',
          'Residual neuromuscular blockade',
          'Increased heart rate',
        ],
        sideEffects: [
          'Prolonged paralysis',
          'Residual weakness',
          'Anaphylaxis',
          'Tachycardia',
          'Hypotension',
        ],
        commonSideEffects: ['Prolonged neuromuscular blockade'],
        seriousSideEffects: ['Anaphylaxis', 'Bronchospasm', 'Cardiac arrest'],
        standardDoseIndication: 'Intubation',
        standardDoseRoute: 'IV',
        standardDose: '0.6-1.2 mg/kg',
        standardDoseFrequency: 'Single dose; may repeat q20-30min',
        standardDoseNotes: 'Onset 60-90 sec; duration 30-60 min',
        geriatricNotes: 'Reduce dose to 0.6 mg/kg',
        maxDailyDose:
            'Individualized; usually as continuous infusion 0.3-0.6 mg/kg/h',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing with caution',
        renalDialysis: 'Not removed; may accumulate with prolonged use',
        renalNotes:
            'Primarily cleared by biliary excretion; minimal renal elimination',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Reduce dose by 75% or avoid',
        hepaticNotes:
            'Metabolized by liver; prolonged effect in hepatic impairment',
      ),

      Drug(
        id: 'RX3120',
        genericName: 'Cisatracurium',
        tradeNames: ['Nimbex'],
        drugClass: 'Non-depolarizing Neuromuscular Blocker',
        mechanism: 'Intermediate-acting non-depolarizing neuromuscular blocker',
        indications: [
          'Adjunct to general anesthesia',
          'ICU mechanical ventilation',
        ],
        contraindications: ['Hypersensitivity'],
        warnings: [
          'Prolonged paralysis',
          'Anaphylaxis',
          'Laudanosine accumulation (seizure risk)',
        ],
        sideEffects: [
          'Prolonged paralysis',
          'Bradycardia',
          'Hypotension',
          'Flushing',
          'Bronchospasm',
        ],
        commonSideEffects: ['Prolonged neuromuscular blockade'],
        seriousSideEffects: [
          'Anaphylaxis',
          'Malignant hyperthermia-like reaction',
          'Seizures (laudanosine toxicity)',
        ],
        standardDoseIndication: 'ICU Paralysis',
        standardDoseRoute: 'IV',
        standardDose: '0.15 mg/kg loading, then 1-3 mcg/kg/min infusion',
        standardDoseFrequency:
            'Continuous infusion; titrate to twitch response',
        standardDoseNotes: 'Hofmann elimination (independent of liver/kidney)',
        geriatricNotes: 'Start at lower end of dosing range',
        maxDailyDose: 'Individualized; typically 0.1-0.3 mg/kg/h',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing (Hofmann elimination)',
        renalNotes: 'Preferred NMB in renal failure; Hofmann elimination',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes: 'Preferred NMB in hepatic failure; Hofmann elimination',
      ),

      // ANTIMICROBIALS
      Drug(
        id: 'RX1972',
        genericName: 'Ceftriaxone',
        tradeNames: ['Rocephin'],
        drugClass: 'Third-generation Cephalosporin',
        mechanism: 'Inhibits bacterial cell wall synthesis',
        indications: [
          'Pneumonia',
          'Meningitis',
          'Sepsis',
          'Skin infections',
          'UTI',
          'Gonorrhea',
          'Surgical prophylaxis',
        ],
        contraindications: [
          'Hypersensitivity to cephalosporins',
          'Neonates with hyperbilirubinemia',
          'Premature neonates',
        ],
        warnings: [
          'Hypersensitivity reactions',
          'Biliary sludge',
          'Pancreatitis',
          'Interaction with calcium (fatal precipitates)',
        ],
        sideEffects: [
          'Diarrhea',
          'Nausea',
          'Vomiting',
          'Rash',
          'Elevated LFTs',
          'Phlebitis',
          'Pseudomembranous colitis',
        ],
        commonSideEffects: ['Diarrhea', 'Rash', 'Elevated LFTs'],
        seriousSideEffects: [
          'Anaphylaxis',
          'Stevens-Johnson syndrome',
          'Hemolytic anemia',
          'Seizures (in renal failure)',
          'Biliary pseudolithiasis',
        ],
        standardDoseIndication: 'Serious Infections',
        standardDoseRoute: 'IM/IV',
        standardDose: '1-2 g',
        standardDoseFrequency: 'q24h',
        standardDoseNotes:
            'Do not exceed 4 g/day; long half-life allows q24h dosing',
        geriatricNotes: 'Normal dosing',
        maxDailyDose: '4 g/day',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Max 2 g/day',
        renalCrclLt10: 'Max 2 g/day; monitor levels if prolonged use',
        renalDialysis: '1 g q24h; give supplement after dialysis',
        renalNotes:
            'Dose adjustment not usually required until CrCl <10; monitor if prolonged use',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes:
            'Biliary excretion; use with caution in severe liver disease',
      ),

      Drug(
        id: 'RX2009',
        genericName: 'Vancomycin',
        tradeNames: ['Vancocin'],
        drugClass: 'Glycopeptide Antibiotic',
        mechanism: 'Inhibits bacterial cell wall synthesis',
        indications: [
          'MRSA infections',
          'Severe penicillin-allergic patients',
          'C. difficile',
          'Endocarditis prophylaxis',
        ],
        contraindications: ['Hypersensitivity'],
        warnings: [
          'Nephrotoxicity',
          'Ototoxicity',
          'Red man syndrome (rapid infusion)',
          'Neutropenia',
        ],
        sideEffects: [
          'Nephrotoxicity',
          'Ototoxicity',
          'Red man syndrome',
          'Phlebitis',
          'Fever',
          'Nausea',
          'Rash',
        ],
        commonSideEffects: ['Nephrotoxicity', 'Red man syndrome', 'Phlebitis'],
        seriousSideEffects: [
          'Acute kidney injury',
          'Irreversible hearing loss',
          'Anaphylaxis',
          'Stevens-Johnson syndrome',
          'Neutropenia',
        ],
        standardDoseIndication: 'MRSA Infection',
        standardDoseRoute: 'IV',
        standardDose: '15-20 mg/kg',
        standardDoseFrequency: 'q8-12h',
        standardDoseNotes:
            'Infuse over at least 60 minutes; monitor trough levels (10-20 mcg/mL)',
        geriatricNotes: 'Reduce dose based on renal function',
        maxDailyDose: '60 mg/kg/day (2-4 g/day)',
        renalCrclGt50: '15-20 mg/kg q8-12h',
        renalCrcl30_50: '15-20 mg/kg q24h',
        renalCrcl10_30: '15-20 mg/kg q24-48h',
        renalCrclLt10: '15-20 mg/kg q48-96h',
        renalDialysis: '15-20 mg/kg after each dialysis session',
        renalNotes: 'Dose adjustment required; monitor trough levels',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing',
        hepaticNotes: 'No dose adjustment required for hepatic impairment',
      ),

      Drug(
        id: 'RX8852',
        genericName: 'Meropenem',
        tradeNames: ['Merrem'],
        drugClass: 'Carbapenem Antibiotic',
        mechanism: 'Inhibits bacterial cell wall synthesis',
        indications: [
          'Intra-abdominal infections',
          'Meningitis',
          'Sepsis',
          'Pneumonia',
          'Skin infections',
        ],
        contraindications: ['Hypersensitivity to carbapenems or beta-lactams'],
        warnings: [
          'Seizures (high doses, renal impairment)',
          'Hypersensitivity reactions',
          'Superinfection',
        ],
        sideEffects: [
          'Seizures',
          'Diarrhea',
          'Nausea',
          'Vomiting',
          'Headache',
          'Thrombophlebitis',
          'Elevated LFTs',
        ],
        commonSideEffects: ['Diarrhea', 'Nausea', 'Headache', 'Elevated LFTs'],
        seriousSideEffects: [
          'Seizures',
          'Anaphylaxis',
          'Stevens-Johnson syndrome',
          'Clostridioides difficile colitis',
          'Hepatic toxicity',
        ],
        standardDoseIndication: 'Serious Infections',
        standardDoseRoute: 'IV',
        standardDose: '500 mg - 1 g',
        standardDoseFrequency: 'q8h',
        standardDoseNotes:
            'Infuse over 15-30 minutes; 3-4 hour infusion for meningitis',
        geriatricNotes: 'Reduce dose based on renal function',
        maxDailyDose: '6 g/day (higher for meningitis)',
        renalCrclGt50: '1 g q8h',
        renalCrcl30_50: '1 g q12h',
        renalCrcl10_30: '500 mg q12h',
        renalCrclLt10: '500 mg q24h',
        renalDialysis: '500 mg after dialysis',
        renalNotes:
            'Significant dose adjustment required; monitor for seizures',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing with caution',
        hepaticChildPughC: 'Reduce dose by 50% or avoid',
        hepaticNotes: 'Use with caution in severe hepatic impairment; monitor',
      ),

      // CARDIOVASCULAR
      Drug(
        id: 'RX3103',
        genericName: 'Norepinephrine',
        tradeNames: ['Levophed'],
        drugClass: 'Vasopressor',
        mechanism: 'Alpha-1 and beta-1 adrenergic agonist',
        indications: [
          'Septic shock',
          'Cardiogenic shock',
          'Hypotension',
          'Neurogenic shock',
        ],
        contraindications: [
          'Hypersensitivity',
          'Hypovolemic shock (correct first)',
        ],
        warnings: [
          'Tissue necrosis if extravasation',
          'Severe hypertension',
          'Cardiac ischemia',
          'Arrhythmias',
        ],
        sideEffects: [
          'Hypertension',
          'Tachycardia',
          'Bradycardia',
          'Arrhythmias',
          'Tissue necrosis',
          'Headache',
          'Anxiety',
        ],
        commonSideEffects: ['Hypertension', 'Bradycardia', 'Tachycardia'],
        seriousSideEffects: [
          'Cardiac ischemia',
          'Mesenteric ischemia',
          'Peripheral ischemia',
          'Pulmonary edema',
          'Cardiac arrest',
        ],
        standardDoseIndication: 'Septic Shock',
        standardDoseRoute: 'IV infusion',
        standardDose: '0.01-0.3 mcg/kg/min',
        standardDoseFrequency: 'Continuous infusion',
        standardDoseNotes:
            'Titrate to MAP target (65-70 mmHg); use central line',
        geriatricNotes: 'Start low; titrate carefully',
        maxDailyDose: 'Individualized; typically 0.01-3 mcg/kg/min',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing; monitor closely',
        renalCrcl10_30: 'Reduce starting dose by 25-50%',
        renalCrclLt10: 'Reduce starting dose by 50%',
        renalDialysis: 'Reduce starting dose; titrate to response',
        renalNotes: 'Renally cleared; may accumulate with severe impairment',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes:
            'Metabolized by MAO and COMT; caution in severe liver disease',
      ),

      Drug(
        id: 'RX3096',
        genericName: 'Epinephrine',
        tradeNames: ['Adrenalin', 'EpiPen'],
        drugClass: 'Sympathomimetic',
        mechanism: 'Alpha and beta adrenergic agonist',
        indications: [
          'Anaphylaxis',
          'Cardiac arrest',
          'Severe asthma',
          'Hypotension/shock',
        ],
        contraindications: [
          'Hypersensitivity (except in life-threatening situations)',
        ],
        warnings: [
          'Tachycardia',
          'Hypertension',
          'Arrhythmias',
          'Myocardial ischemia',
          'Pulmonary edema',
        ],
        sideEffects: [
          'Tachycardia',
          'Hypertension',
          'Arrhythmias',
          'Angina',
          'Headache',
          'Tremor',
          'Anxiety',
          'Hyperglycemia',
        ],
        commonSideEffects: ['Tachycardia', 'Hypertension', 'Anxiety', 'Tremor'],
        seriousSideEffects: [
          'Ventricular fibrillation',
          'Myocardial infarction',
          'Pulmonary edema',
          'Stroke',
          'Intracranial hemorrhage',
        ],
        standardDoseIndication: 'Anaphylaxis',
        standardDoseRoute: 'IM/IV',
        standardDose: '0.3-0.5 mg (IM), 0.1-0.25 mg (IV)',
        standardDoseFrequency: 'Single dose; may repeat q5-15min',
        standardDoseNotes:
            'IM for anaphylaxis (thigh); IV push for cardiac arrest',
        geriatricNotes:
            'Use lowest effective dose; monitor for cardiac effects',
        maxDailyDose: 'Individualized; usually limited to acute situations',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing with caution',
        renalCrclLt10: 'Normal dosing with caution',
        renalDialysis: 'Normal dosing',
        renalNotes: 'Metabolized rapidly; no dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes: 'Metabolized by MAO; caution in severe liver disease',
      ),

      Drug(
        id: 'RX3173',
        genericName: 'Dopamine',
        tradeNames: ['Intropin'],
        drugClass: 'Vasopressor/Inotrope',
        mechanism:
            'Dopamine receptor agonist; alpha and beta adrenergic effects (dose-dependent)',
        indications: [
          'Hypotension/shock',
          'Cardiac decompensation',
          'Bradycardia (high dose)',
        ],
        contraindications: [
          'Hypersensitivity',
          'Pheochromocytoma',
          'Untreated tachyarrhythmias',
          'Ventricular fibrillation',
        ],
        warnings: [
          'Tissue necrosis if extravasation',
          'Arrhythmias',
          'Severe hypertension',
          'Ischemia',
        ],
        sideEffects: [
          'Tachycardia',
          'Arrhythmias',
          'Hypertension',
          'Nausea',
          'Vomiting',
          'Headache',
          'Tissue necrosis',
        ],
        commonSideEffects: [
          'Tachycardia',
          'Nausea',
          'Headache',
          'Hypertension (at higher doses)',
        ],
        seriousSideEffects: [
          'Cardiac ischemia',
          'Mesenteric ischemia',
          'Gangrene (extravasation)',
          'Ventricular arrhythmias',
        ],
        standardDoseIndication: 'Shock/Hypotension',
        standardDoseRoute: 'IV infusion',
        standardDose: '2-20 mcg/kg/min',
        standardDoseFrequency: 'Continuous infusion',
        standardDoseNotes:
            'Renal dose: 0.5-3 mcg/kg/min; Inotropic: 2-10 mcg/kg/min; Vasopressor: >10 mcg/kg/min',
        geriatricNotes: 'Start low; titrate slowly',
        maxDailyDose: 'Individualized; typically 2-50 mcg/kg/min',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing; monitor closely',
        renalCrcl10_30: 'Reduce starting dose by 25-50%',
        renalCrclLt10: 'Reduce starting dose by 50%',
        renalDialysis: 'Reduce starting dose; titrate to response',
        renalNotes: 'Renally cleared; dose adjustment may be needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes:
            'Metabolized by MAO and COMT; caution in severe liver disease',
      ),

      Drug(
        id: 'RX3133',
        genericName: 'Dobutamine',
        tradeNames: ['Dobutrex'],
        drugClass: 'Inotrope',
        mechanism: 'Beta-1 adrenergic agonist',
        indications: [
          'Cardiogenic shock',
          'Acute decompensated heart failure',
          'Cardiac stress testing',
        ],
        contraindications: [
          'Hypersensitivity',
          'Idiopathic hypertrophic subaortic stenosis',
        ],
        warnings: [
          'Tachycardia',
          'Arrhythmias',
          'Hypotension',
          'Myocardial ischemia',
        ],
        sideEffects: [
          'Tachycardia',
          'Arrhythmias',
          'Hypotension',
          'Angina',
          'Headache',
          'Nausea',
          'Tremor',
        ],
        commonSideEffects: ['Tachycardia', 'Headache', 'Nausea', 'Hypotension'],
        seriousSideEffects: [
          'Ventricular fibrillation',
          'Myocardial ischemia',
          'Cardiac arrest',
          'Severe hypotension',
        ],
        standardDoseIndication: 'Cardiogenic Shock',
        standardDoseRoute: 'IV infusion',
        standardDose: '2.5-20 mcg/kg/min',
        standardDoseFrequency: 'Continuous infusion',
        standardDoseNotes: 'Titrate to response; monitor ECG and hemodynamics',
        geriatricNotes: 'Start low (2.5 mcg/kg/min); titrate slowly',
        maxDailyDose: 'Individualized; typically 2.5-40 mcg/kg/min',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing with caution',
        renalDialysis: 'Normal dosing',
        renalNotes: 'Metabolized by COMT; minimal renal clearance',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing with caution',
        hepaticNotes:
            'Metabolized primarily in tissues; caution in severe liver disease',
      ),

      Drug(
        id: 'RX3165',
        genericName: 'Milrinone',
        tradeNames: ['Primacor'],
        drugClass: 'Phosphodiesterase-3 Inhibitor',
        mechanism: 'Inhibits PDE3, increasing cAMP and calcium uptake',
        indications: ['Acute decompensated heart failure', 'Cardiogenic shock'],
        contraindications: [
          'Hypersensitivity',
          'Severe obstructive cardiomyopathy',
        ],
        warnings: ['Arrhythmias', 'Hypotension', 'Thrombocytopenia'],
        sideEffects: [
          'Arrhythmias',
          'Hypotension',
          'Headache',
          'Thrombocytopenia',
          'Nausea',
        ],
        commonSideEffects: ['Headache', 'Hypotension', 'Arrhythmias'],
        seriousSideEffects: [
          'Ventricular arrhythmias',
          'Cardiac arrest',
          'Severe thrombocytopenia',
        ],
        standardDoseIndication: 'Acute Heart Failure',
        standardDoseRoute: 'IV',
        standardDose:
            'Loading: 50 mcg/kg over 10 min, then 0.375-0.75 mcg/kg/min',
        standardDoseFrequency: 'Continuous infusion',
        standardDoseNotes:
            'Do not give loading if already on oral PDE inhibitors',
        geriatricNotes: 'Reduce dose by 50%; avoid loading dose',
        maxDailyDose: '1.13 mg/kg/day (0.75 mcg/kg/min)',
        renalCrclGt50: '0.375-0.75 mcg/kg/min',
        renalCrcl30_50: '0.375-0.5 mcg/kg/min',
        renalCrcl10_30: '0.125-0.375 mcg/kg/min',
        renalCrclLt10: 'Avoid or use 0.125 mcg/kg/min',
        renalDialysis: 'Avoid or use 0.125 mcg/kg/min',
        renalNotes: 'Significantly renally cleared; dose adjustment required',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Reduce dose by 25-50%',
        hepaticChildPughC: 'Reduce dose by 50% or avoid',
        hepaticNotes: 'Metabolized in liver; use with caution',
      ),

      Drug(
        id: 'RX1982',
        genericName: 'Amiodarone',
        tradeNames: ['Cordarone', 'Pacerone'],
        drugClass: 'Antiarrhythmic (Class III)',
        mechanism:
            'Potassium channel blocker; also sodium, calcium channel blockade, beta-blockade',
        indications: [
          'Ventricular tachycardia',
          'Ventricular fibrillation',
          'Atrial fibrillation',
          'Supraventricular tachycardia',
        ],
        contraindications: [
          'Severe sinus node dysfunction',
          'Second- or third-degree AV block',
          'Bradycardia causing syncope',
        ],
        warnings: [
          'QT prolongation',
          'Torsades de pointes',
          'Pulmonary toxicity',
          'Hepatotoxicity',
          'Thyroid dysfunction',
          'Bradyarrhythmias',
        ],
        sideEffects: [
          'QT prolongation',
          'Bradycardia',
          'Hypotension',
          'Nausea',
          'Vomiting',
          'Fatigue',
          'Photosensitivity',
          'Thyroid dysfunction',
        ],
        commonSideEffects: [
          'Bradycardia',
          'QT prolongation',
          'Hypotension',
          'Fatigue',
        ],
        seriousSideEffects: [
          'Pulmonary fibrosis',
          'Acute liver toxicity',
          'Torsades de pointes',
          'Thyroid storm',
          'Optic neuropathy',
          'Proarrhythmia',
        ],
        standardDoseIndication: 'Cardiac Arrest',
        standardDoseRoute: 'IV',
        standardDose: '300 mg bolus, then 150 mg',
        standardDoseFrequency:
            'Bolus, then infusion 1 mg/min for 6 hours, then 0.5 mg/min',
        standardDoseNotes: 'Maximum total dose 2.2 g in 24 hours',
        geriatricNotes: 'Use lower end of dosing range; monitor closely',
        maxDailyDose: '2.2 g in first 24 hours',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'No dose adjustment needed for renal impairment',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes: 'Hepatic metabolism; caution in liver disease',
      ),

      Drug(
        id: 'RX3162',
        genericName: 'Lidocaine',
        tradeNames: ['Xylocaine'],
        drugClass: 'Antiarrhythmic (Class IB), Local Anesthetic',
        mechanism: 'Sodium channel blocker',
        indications: [
          'Ventricular arrhythmias',
          'Local anesthesia',
          'Neuropathic pain',
        ],
        contraindications: [
          'Hypersensitivity',
          'Adams-Stokes syndrome',
          'Severe AV block',
        ],
        warnings: [
          'CNS toxicity',
          'Cardiovascular collapse',
          'Methemoglobinemia',
        ],
        sideEffects: [
          'CNS toxicity (dizziness, seizures)',
          'Hypotension',
          'Bradycardia',
          'Nausea',
          'Metallic taste',
          'Tinnitus',
        ],
        commonSideEffects: [
          'Dizziness',
          'Nausea',
          'Metallic taste',
          'Tinnitus',
          'Hypotension',
        ],
        seriousSideEffects: [
          'Seizures',
          'Cardiac arrest',
          'Respiratory depression',
          'Coma',
          'Methemoglobinemia',
        ],
        standardDoseIndication: 'Ventricular Arrhythmia',
        standardDoseRoute: 'IV',
        standardDose: '1-1.5 mg/kg',
        standardDoseFrequency: 'Bolus, then infusion 1-4 mg/min',
        standardDoseNotes: 'Onset <1 min; duration 10-20 minutes',
        geriatricNotes:
            'Reduce loading dose to 0.5-1 mg/kg; reduce infusion by 50%',
        maxDailyDose: 'Individualized; typically 1-4 mg/min infusion',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Reduce infusion by 50%',
        renalCrcl10_30: 'Reduce infusion by 50-75%',
        renalCrclLt10: 'Avoid or reduce infusion by 75%',
        renalDialysis: 'Reduce infusion by 50%',
        renalNotes: 'Renally cleared metabolites; dose reduction needed',
        hepaticChildPughA: 'Reduce dose by 25%',
        hepaticChildPughB: 'Reduce dose by 50%',
        hepaticChildPughC: 'Avoid or reduce dose by 75%',
        hepaticNotes: 'Hepatic metabolism; significant dose adjustment needed',
      ),

      // STEROIDS
      Drug(
        id: 'RX1983',
        genericName: 'Methylprednisolone',
        tradeNames: ['Solu-Medrol', 'Medrol'],
        drugClass: 'Corticosteroid',
        mechanism: 'Anti-inflammatory; immunosuppressant',
        indications: [
          'Inflammatory conditions',
          'Autoimmune disorders',
          'Allergic reactions',
          'Asthma exacerbation',
          'COPD exacerbation',
          'Spinal cord injury',
        ],
        contraindications: [
          'Hypersensitivity',
          'Systemic fungal infection',
          'Live vaccines (severe immunosuppression)',
        ],
        warnings: [
          'Immunosuppression',
          'Adrenal suppression',
          'Hyperglycemia',
          'Fluid retention',
          'Psychiatric effects',
          'Osteonecrosis',
        ],
        sideEffects: [
          'Hyperglycemia',
          'Fluid retention',
          'Hypertension',
          'Mood changes',
          'Insomnia',
          'Increased appetite',
          'Weight gain',
        ],
        commonSideEffects: [
          'Hyperglycemia',
          'Insomnia',
          'Mood changes',
          'Fluid retention',
        ],
        seriousSideEffects: [
          'Adrenal crisis',
          'Anaphylaxis',
          'Severe psychiatric reactions',
          'Osteonecrosis',
          'Severe infections',
          'Peptic ulcer disease',
        ],
        standardDoseIndication: 'Anti-inflammatory',
        standardDoseRoute: 'IV/IM/PO',
        standardDose: '10-250 mg',
        standardDoseFrequency: 'q6h (IV), daily (PO)',
        standardDoseNotes: 'Taper dose gradually when discontinuing',
        geriatricNotes:
            'Use lowest effective dose; monitor for glucose, fluid status',
        maxDailyDose: 'Varies by condition (up to several grams in shock)',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'No dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing with caution',
        hepaticChildPughC: 'Reduce dose by 25-50%',
        hepaticNotes: 'Use with caution in severe liver disease',
      ),

      Drug(
        id: 'RX3548',
        genericName: 'Dexamethasone',
        tradeNames: ['Decadron', 'Dexamethasone Intensol'],
        drugClass: 'Corticosteroid',
        mechanism: 'Anti-inflammatory; immunosuppressant',
        indications: [
          'Inflammatory conditions',
          'Cerebral edema',
          'Chemotherapy-induced nausea',
          'COVID-19 (severe)',
          'Diagnostic testing',
        ],
        contraindications: [
          'Hypersensitivity',
          'Systemic fungal infection',
          'Live vaccines',
        ],
        warnings: [
          'Immunosuppression',
          'Adrenal suppression',
          'Hyperglycemia',
          'Psychiatric effects',
        ],
        sideEffects: [
          'Hyperglycemia',
          'Insomnia',
          'Mood changes',
          'Fluid retention',
          'Increased appetite',
          'Weight gain',
        ],
        commonSideEffects: ['Hyperglycemia', 'Insomnia', 'Fluid retention'],
        seriousSideEffects: [
          'Adrenal crisis',
          'Severe psychiatric reactions',
          'Anaphylaxis',
          'Severe infections',
        ],
        standardDoseIndication: 'Anti-inflammatory',
        standardDoseRoute: 'IV/IM/PO',
        standardDose: '0.5-10 mg',
        standardDoseFrequency: 'q6h (IV/IM), daily (PO)',
        standardDoseNotes: 'Long half-life (36-54 hours)',
        geriatricNotes: 'Use lowest effective dose; monitor glucose',
        maxDailyDose: 'Varies (up to 100 mg/day for cerebral edema)',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'No dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing',
        hepaticNotes: 'Minimal hepatic metabolism; no dose adjustment needed',
      ),

      // RESPIRATORY
      Drug(
        id: 'RX7952',
        genericName: 'Albuterol',
        tradeNames: ['Proventil', 'Ventolin', 'ProAir'],
        drugClass: 'Beta-2 Agonist',
        mechanism: 'Beta-2 adrenergic receptor agonist',
        indications: [
          'Asthma',
          'COPD',
          'Bronchospasm',
          'Exercise-induced bronchospasm',
        ],
        contraindications: ['Hypersensitivity'],
        warnings: [
          'Paradoxical bronchospasm',
          'Tachycardia',
          'Hypokalemia',
          'Tremor',
          'Hyperglycemia',
        ],
        sideEffects: [
          'Tremor',
          'Tachycardia',
          'Palpitations',
          'Headache',
          'Nervousness',
          'Hypokalemia',
          'Hyperglycemia',
        ],
        commonSideEffects: ['Tremor', 'Tachycardia', 'Headache', 'Nervousness'],
        seriousSideEffects: [
          'Paradoxical bronchospasm',
          'Cardiac arrhythmias',
          'Severe hypokalemia',
          'Myocardial ischemia',
        ],
        standardDoseIndication: 'Bronchospasm',
        standardDoseRoute: 'Inhalation/Nebulization',
        standardDose: '2-4 puffs MDI, 2.5 mg neb',
        standardDoseFrequency: 'q4-6h PRN',
        standardDoseNotes:
            'Continuous nebs: 10-15 mg/hour for severe bronchospasm',
        geriatricNotes: 'Start with lower doses; monitor for cardiac effects',
        maxDailyDose: '16 mg/day',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'No dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing',
        hepaticNotes: 'Minimal hepatic metabolism; no dose adjustment needed',
      ),

      Drug(
        id: 'RX1991',
        genericName: 'Ipratropium',
        tradeNames: ['Atrovent'],
        drugClass: 'Anticholinergic',
        mechanism: 'Muscarinic receptor antagonist',
        indications: ['COPD', 'Asthma (adjunct)', 'Rhinitis'],
        contraindications: ['Hypersensitivity to atropine or derivatives'],
        warnings: [
          'Paradoxical bronchospasm',
          'Urinary retention',
          'Acute angle-closure glaucoma',
          'Tachycardia',
        ],
        sideEffects: [
          'Dry mouth',
          'Cough',
          'Bronchospasm',
          'Headache',
          'Nausea',
          'Urinary retention',
          'Tachycardia',
        ],
        commonSideEffects: ['Dry mouth', 'Cough', 'Headache'],
        seriousSideEffects: [
          'Paradoxical bronchospasm',
          'Angle-closure glaucoma',
          'Urinary retention',
          'Anaphylaxis',
        ],
        standardDoseIndication: 'COPD',
        standardDoseRoute: 'Inhalation/Nebulization',
        standardDose: '2 puffs MDI, 500 mcg neb',
        standardDoseFrequency: 'q6-8h',
        standardDoseNotes: 'Can combine with albuterol',
        geriatricNotes:
            'Use with caution; monitor for urinary retention and glaucoma',
        maxDailyDose: '12 puffs/day MDI, 2 mg/day neb',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Normal dosing',
        renalCrclLt10: 'Normal dosing',
        renalDialysis: 'Normal dosing',
        renalNotes: 'Minimal systemic absorption; no dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Normal dosing',
        hepaticChildPughC: 'Normal dosing',
        hepaticNotes: 'Minimal hepatic metabolism; no dose adjustment needed',
      ),

      // ANTICOAGULANTS/ANTIPLATELETS
      Drug(
        id: 'RX3291',
        genericName: 'Heparin',
        tradeNames: ['Heparin Lock Flush', 'Hep-Lock'],
        drugClass: 'Anticoagulant',
        mechanism: 'Potentiates antithrombin III',
        indications: [
          'VTE prophylaxis',
          'VTE treatment',
          'Atrial fibrillation',
          'Acute coronary syndrome',
          'ECMO',
          'Hemodialysis',
        ],
        contraindications: [
          'Active bleeding',
          'Heparin-induced thrombocytopenia (HIT)',
          'Severe thrombocytopenia',
        ],
        warnings: [
          'Bleeding',
          'Heparin-induced thrombocytopenia (HIT)',
          'Osteoporosis with long-term use',
          'Hyperkalemia',
        ],
        sideEffects: [
          'Bleeding',
          'Heparin-induced thrombocytopenia',
          'Osteoporosis',
          'Hypersensitivity',
          'Hyperkalemia',
          'Elevated LFTs',
        ],
        commonSideEffects: ['Bleeding', 'HIT', 'Elevated LFTs'],
        seriousSideEffects: [
          'Major bleeding (intracranial, retroperitoneal)',
          'HIT with thrombosis',
          'Anaphylaxis',
          'Spinal/epidural hematoma',
        ],
        standardDoseIndication: 'VTE Prophylaxis',
        standardDoseRoute: 'SC',
        standardDose: '5000 units',
        standardDoseFrequency: 'q8-12h',
        standardDoseNotes:
            'Monitor aPTT for therapeutic dosing (target 60-80 sec)',
        geriatricNotes: 'Reduce dose; monitor aPTT closely; bleeding risk',
        maxDailyDose: 'Individualized based on aPTT',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing',
        renalCrcl10_30: 'Reduce dose by 25-50%; monitor aPTT',
        renalCrclLt10: 'Avoid or reduce dose by 50%; monitor aPTT',
        renalDialysis: 'Reduce dose by 50%; monitor aPTT',
        renalNotes: 'Dose adjustment needed in severe renal impairment',
        hepaticChildPughA: 'Normal dosing; monitor aPTT',
        hepaticChildPughB: 'Reduce dose by 25-50%; monitor aPTT',
        hepaticChildPughC: 'Reduce dose by 50% or avoid; monitor aPTT',
        hepaticNotes: 'Use with caution in severe liver disease; bleeding risk',
      ),

      Drug(
        id: 'RX8630',
        genericName: 'Enoxaparin',
        tradeNames: ['Lovenox'],
        drugClass: 'Low Molecular Weight Heparin',
        mechanism:
            'Potentiates antithrombin III (more predictable than heparin)',
        indications: [
          'VTE prophylaxis',
          'VTE treatment',
          'Acute coronary syndrome',
          'Medical immobilization',
        ],
        contraindications: [
          'Active bleeding',
          'HIT',
          'Severe thrombocytopenia',
          'Hypersensitivity',
        ],
        warnings: [
          'Bleeding',
          'HIT (cross-reactivity)',
          'Epidural/spinal hematoma',
          'Hyperkalemia',
          'Thrombocytopenia',
        ],
        sideEffects: [
          'Bleeding',
          'Thrombocytopenia',
          'Elevated LFTs',
          'Injection site reaction',
          'Hyperkalemia',
        ],
        commonSideEffects: [
          'Bleeding',
          'Injection site bruising',
          'Elevated LFTs',
        ],
        seriousSideEffects: [
          'Major bleeding',
          'Epidural/spinal hematoma',
          'HIT',
          'Anaphylaxis',
        ],
        standardDoseIndication: 'VTE Prophylaxis',
        standardDoseRoute: 'SC',
        standardDose: '40 mg',
        standardDoseFrequency: 'Daily',
        standardDoseNotes: 'No monitoring needed in most cases',
        geriatricNotes:
            'Monitor closely; bleeding risk; dose adjust if CrCl <30',
        maxDailyDose: '40 mg/day prophylaxis; 1 mg/kg q12h treatment',
        renalCrclGt50: 'Normal dosing',
        renalCrcl30_50: 'Normal dosing with caution',
        renalCrcl10_30: 'Reduce dose to 30 mg/day prophylaxis',
        renalCrclLt10: 'Avoid or 30 mg/day; consider alternative',
        renalDialysis: 'Avoid or use 30 mg/day; consider UFH instead',
        renalNotes: 'Significant renal clearance; dose adjustment needed',
        hepaticChildPughA: 'Normal dosing',
        hepaticChildPughB: 'Use with caution; monitor',
        hepaticChildPughC: 'Use with extreme caution or avoid',
        hepaticNotes:
            'Metabolized in liver; use with caution in severe disease',
      ),
    ];
  }
}
